global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: verifier
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['verifier:8080']